### ISSUE TITLE
kubler/log-collector fails to build

### ISSUE THREAD

**Issue by Wuodan** [edannenberg/kubler#153]
Just an info that kubler/log-collector fails to build when running `kubler build kubler`.

Not really using the image at the moment.

**Environment:**
* commit: 854c0cc5c817a563c8a3789a4564164e02b62ccd
* portage and stage3:
```
# docker image ls | grep kubler-gentoo | grep -v latest | awk '{print $1 ":" $2}'
kubler-gentoo/stage3-amd64-musl-hardened:20181104
kubler-gentoo/stage3-amd64-hardened-nomultilib:20181113T214502Z
kubler-gentoo/portage:20181218
```

**Log:**
```
--> build image kubler/log-collector
--> phase 2: build kubler/log-collector:20181130
Sending build context to Docker daemon  11.02MB
Step 1/10 : FROM kubler/ruby-gcc
 ---> 512ad1950aa6
Step 2/10 : LABEL maintainer Erik Dannenberg <erik.dannenberg@xtrade-gmbh.de>
 ---> Running in 9892c261238c
Removing intermediate container 9892c261238c
 ---> 3b1ab3b0439d
Step 3/10 : ADD rootfs.tar /
 ---> beda2c1f3334
Step 4/10 : RUN gem install fluentd --no-ri --no-rdoc
 ---> Running in e98dfbcd370b
Building native extensions. This could take a while...
ERROR:  Error installing fluentd:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib64/ruby/gems/2.4.0/gems/msgpack-1.2.4/ext/msgpack
/usr/bin/ruby24 -r ./siteconf20181218-1-3p0296.rb extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)24
/usr/lib64/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib64/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:1096:in `block in have_header'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:946:in `block in checking_for'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:321:in `open'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:945:in `checking_for'
        from /usr/lib64/ruby/2.4.0/mkmf.rb:1095:in `have_header'
        from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib64/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/msgpack-1.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib64/ruby/gems/2.4.0/gems/msgpack-1.2.4 for inspection.
Results logged to /usr/local/lib64/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/msgpack-1.2.4/gem_make.out
The command '/bin/sh -c gem install fluentd --no-ri --no-rdoc' returned a non-zero code: 1
fatal: failed to build kubler/images/log-collector
```

**Comment by edannenberg** [comment]
Thanks for the heads up. Just did a rebuild with latest stage3 / portage tree, no issues. Maybe already fixed upstream?

**Comment by Wuodan** [comment]
kubler/log-collector just built here -> closing this.
Failed with 2 different stage3 before ... I think you're right about upstream fixing it. Thank you for looking at it.
