### ISSUE TITLE
permission thing

### ISSUE THREAD

**Issue by dtuser007** [edannenberg/kubler#237]
Hi gentleman,
I run kubler as non-root user 'pdm', id 1001, I set up an arm64 builder.sh from scratch:
```
configure_builder() {
    fix_portage_profile_symlink
    eselect news read new 1> /dev/null
    emerge app-portage/flaggie app-portage/eix app-portage/gentoolkit
    configure_eix
    mkdir -p /etc/portage/package.{accept_keywords,unmask,mask,use}
    touch /etc/portage/package.accept_keywords/flaggie
    echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen
    locale-gen
    echo 'LANG="en_US.utf8"' > /etc/env.d/02locale
    env-update
    source /etc/profile
    [[ -f /usr/"${_LIB}"/misc/ssh-keysign ]] && rm /usr/"${_LIB}"/misc/ssh-keysign
    update_use 'dev-vcs/git' '-perl'
    update_use 'app-crypt/pinentry' '+ncurses'
    update_use 'sys-devel/binutils' '+gold'
    emerge dev-vcs/git app-eselect/eselect-repository app-misc/jq app-shells/bash-completion
    [[ "${BOB_UPDATE_WORLD}" == true ]] && emerge -vuND world
    add_overlay kubler https://github.com/edannenberg/kubler-overlay.git
    emerge dev-lang/go
}
```
I repeatedly get this FATAL ERROR when runing 'kubler clean' and ':kubler build -C af23/asterisk'
```
»»»»»[af23/arm64]» tag image af23/arm64:latest
»»»»»[af23/arm64]» remove untagged images
»»»»»[af23/arm64]» remove unused volumes
/usr/share/kubler/lib/core.sh: line 735: /home/pdm/af23/builder/arm64/PACKAGES.md: Keine Berechtigung (translated: no permisson)
»[✘]»[af23/arm64]» fatal: Failed to generate PACKAGES.md for af23/arm64
```

File perms seen as user 'root' are: -rw-r--r-- 1 1001001000 1001001000 139 25. Jun 23:48 /home/pdm/af23/builder/arm64/PACKAGES.md
subuid: pdm:1001000000:1000000
subgid: pdm:1001000000:1000000

Any idea to help me? Thanks.

**Comment by r7l** [comment]
The file will be created for every image within your namespace directories. That's not done within the Docker images but within the image directories on your host system. Have you checked if your user is able to write within those directories? The script is just using `echo` to place the content into the file. It might also work if you create these files yourself and set the permissions for it.

**Comment by dtuser007** [comment]
Thanks for reply!
The user has access, the whole directory tree is created by kubler anyhow when called as that particular user:
  drwxr-xr-x 2 pdm        pdm        4096 25. Jun 23:48 .
As I wrote above, the owner/group of 'PACKAGE.md' is _NOT_ that of my user but shows the ids mapped to that user in rootless containers (/etc/subuid and /etc/subgid). All other files still have the orginal ownership. This is what I stumbled upon and what IMHO causes the error.
BTW I found a chown command in kubler/engine/docker/bob-core/build-root.sh, in the function generate_documentation(), but I do not understand what it tweaks.

**Comment by r7l** [comment]
The other files aren't touched. Looking at your error message, it doesn't seem to come from `engine/docker/bob-core/build-root.sh` but instead it's from `build_image` in `engine/docker.sh` as it would call `add_documentation_header` which is in `lib/core.sh` where your error message comes from:

```
/usr/share/kubler/lib/core.sh: line 735: /home/pdm/af23/builder/arm64/PACKAGES.md: Keine Berechtigung (translated: no permisson)
```

I am not entirely sure if this part of the code is called from within or outside of Docker. I haven't build Kubler and would have to dig deeper through the code which i don't have to time today. Sorry! We might have to wait for the main developer @edannenberg. 

The issues should not exist if you're using Kubler with `root`. That's what i do (sudo mostly). Unless you've follow the steps for [rootless Docker](https://docs.docker.com/engine/security/rootless/) it's actually even a security issue to add your user to the `docker` group. The user turns into [a root user](https://gist.github.com/nileshsimaria/82ed9eaf116832a8d7128ecb08dddc11) due to [design choices](https://docs.docker.com/engine/security/#docker-daemon-attack-surface) made by Docker.

**Comment by dtuser007** [comment]
I am using podman, so the security issue is not existent.
Going to use kubler as root now. It should still be possible to run the kubler-built images as non-root user I hope.
Thank you.

**Comment by r7l** [comment]
Haven't used Podman so far but you're correct. It should work with for people using normal users. Even with Docker.

**Comment by edannenberg** [comment]
> BTW I found a chown command in kubler/engine/docker/bob-core/build-root.sh, in the function generate_documentation(), but I do not understand what it tweaks.

To work around such permission issues (the build container runs as root inside) the build script passes the user host id and gid as variables to the build container, which can than be used in the container. I run kubler as non-root all the time, so this looks like a podman issue.

This looks like a good solution to your problem: https://stackoverflow.com/a/70774211

**Comment by edannenberg** [comment]
Did you try it? Should be ok I think as the podman basically extends the docker engine with very few changes.

**Comment by dtuser007** [comment]
not yet, needs more time. I send feedback later.

**Comment by dtuser007** [comment]
still struggling, may be the whole thing is to complicated for me;-)
»»»»»[portage]» bootstrap kubler-gentoo/portage image
[1/2] STEP 1/4: FROM busybox:latest AS builder
[1/2] STEP 2/4: COPY portage-20230629.tar.xz /
--> Using cache bd93c66234be021a4b59bd4301c3842c58dbad31615f5b1a4b206b2ae2f515fc
--> bd93c66234be
[1/2] STEP 3/4: COPY patches/ /patches
--> Using cache bf28782bce5e285c072def7c4186b9e228d27fff30cbebdf0380cb88246406c5
--> bf28782bce5e
[1/2] STEP 4/4: RUN set -x &&     mkdir -p /var/db/repos/ &&     xzcat /portage-20230629.tar.xz | tar -xf - -C /var/db/repos &&     mv /var/db/repos/portage /var/db/repos/gentoo &&     mkdir -p /var/db/repos/gentoo/metadata &&     rm /portage-20230629.tar.xz &&     cd /var/db/repos/gentoo &&     patch -p1 -i /patches/0002* &&     patch -p1 -i /patches/0003* &&     patch -p1 -i /patches/0004*
+ mkdir -p /var/db/repos/
+ xzcat /portage-20230629.tar.xz
+ tar -xf - -C /var/db/repos
+ mv /var/db/repos/portage /var/db/repos/gentoo
+ mkdir -p /var/db/repos/gentoo/metadata
+ rm /portage-20230629.tar.xz
+ cd /var/db/repos/gentoo
+ patch -p1 -i /patches/0002-Revert-user-info.eclass-Fixing-user-group-creation-w.patch
patching file eclass/user-info.eclass
+ patch -p1 -i /patches/0003-Revert-acct-user.eclass-Fixing-user-group-creation-w.patch
patching file eclass/acct-user.eclass
Hunk 2 FAILED 359/352

Anyhow, the 'permission thing' seems to be rectified, so we may close it.

**Comment by r7l** [comment]
@dtuser007 From time to time Gentoo maintainers edit the user eclasses and if that happens Kubler needs patching. Can you try using most recent commit from Kubler repo as this error was fixed 2 days ago. I'd guess there wasn't a new release since then.

**Comment by dtuser007** [comment]
@r7l thank you, the patches ran through now with the latest git.
I'll see if it stops again...

**Comment by dtuser007** [comment]
with 'BUILDER_DOCKER_ARGS_GLOBAL=('--userns=keep-id')' I get:

Successfully tagged localhost/af23/amd64-core:20230629
[..]
»»»»»[af23/amd64-core]» remove unused volumes
»[✔]»[af23/amd64-core]» done.
»»»»»[af23/amd64]» bootstrap builder environment
{"msg":"exec container process `/usr/local/bin/kubler-build-root`: Permission denied","level":"error","time":"2023-06-29T07:57:12.102185Z"}
»[✘]»[af23/amd64]» fatal: Failed to run image af23/amd64-core:20230629
»[✘]»[af23/amd64]» removing rootfs-builder-af23-amd64-22896-8225, NO_CLEANUP env prevents this

when commenting 'BUILDER_DOCKER_ARGS_GLOBAL' out and starting the procedure in a fresh namespace it fails again with permission denied:

Successfully tagged localhost/af23/amd64-core:20230627
98ce6cbf5f8d1e4717db17b2a613456d8c936e074e3d987a82cc09eed9cf4c1c
»»»»»[af23/amd64-core]» tag image af23/amd64-core:latest
[..]
»»»»»[af23/amd64-core]» remove unused volumes
»[✔]»[af23/amd64-core]» done.
»»»»»[af23/amd64]» bootstrap builder environment
switching portage profile to: /var/db/repos/gentoo/profiles/default/linux/amd64/17.1

Performing Global Updates
[...]
Calculating dependencies... done!
Dependency resolution took 2.66 s.

>>> Verifying ebuild manifests
>>> Emerging (1 of 21) app-shells/push-3.4::gentoo
>>> Failed to emerge app-shells/push-3.4, Log file:
>>>  '/var/tmp/portage/app-shells/push-3.4/temp/build.log'
>>> Jobs: 0 of 21 complete, 1 failed                Load avg: 1.43, 1.29, 1.07
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 647, in _recursive_file_list
    st = os.stat(fullpath)
         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/__init__.py", line 280, in __call__
    rval = self._func(*wrapped_args, **wrapped_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: b'/etc/portage/mirrors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/portage/util/_async/ForkProcess.py", line 162, in _bootstrap
    sys.exit(self._run())
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_emerge/EbuildFetcher.py", line 271, in _run
    if fetch(
       ^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/package/ebuild/fetch.py", line 910, in fetch
    custommirrors = grabdict(
                    ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 428, in grabdict
    for x in grablines(myfilename, recursive):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 675, in grablines
    for f in _recursive_file_list(myfilename):
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 649, in _recursive_file_list
    onerror(e)
  File "/usr/lib/python3.11/site-packages/portage/util/__init__.py", line 638, in onerror
    raise PermissionDenied(path)
portage.exception.PermissionDenied: /etc/portage/mirrors

It seems I definitly must switch to root builds. I will setup a vm on a faster machine for testing that way before moving to my arm64 target.

**Comment by edannenberg** [comment]
> PermissionError: [Errno 13] Permission denied: b'/etc/portage/mirrors'

That does look a bit weird as this is not a host file, so there should be no permission issue if you are running as root inside the build container, which should always be the case. All you need to do to fix your inital permission problem is to ensure that `BOB_HOST_UID` and `BOB_HOST_GID` in the build container match your actual host user `ÙID` and `GID`, not whatever pseudo nonroot-id podman is using.

You can check this easily without building, as long as you a have core builder image, which seems to be the case:

```
host-shell # echo $UID
1000
kubler build -i af23/amd64
build-container-shell / # echo $BOB_HOST_UID
1000
```

**Comment by edannenberg** [comment]
Closing due to inactivity. Feel free to reopen.
